ToDoList_Project/ToDoList_Project/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('todolist/', include('todolist.urls'))
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

ToDoList_Project/todolist/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='todolist'
urlpatterns = [
    path('', views.TasksListView.as_view(), name='all'),
    path('task/<int:pk>', views.TasksDetailView.as_view(), name='task_detail'),
    path('task/create',
        views.TasksCreateView.as_view(success_url=reverse_lazy('todolist:all')), name='task_create'),
    path('task/<int:pk>/update',
        views.TasksUpdateView.as_view(success_url=reverse_lazy('todolist:all')), name='task_update'),
    path('task/<int:pk>/delete',
        views.TasksDeleteView.as_view(success_url=reverse_lazy('todolist:all')), name='task_delete'),

    path('task/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='task_favorite'),
    path('task/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='task_unfavorite'),
]

ToDoList_Project/todolist/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from taggit.managers import TaggableManager

class Task(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Fav', related_name='favorite_tasks')
    tags = TaggableManager(blank=True)



    # Shows up in the admin list
    def __str__(self):
        return self.title



class Fav(models.Model) :
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="todolist_user")
    
    class Meta:
        unique_together = ('task', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.task.title[:10])

ToDoList_Project/todolist/forms.py
from django import forms
from todolist.models import Task


# Create the form class.
class CreateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'text', 'tags']

ToDoList_Project/todolist/views.py
from todolist.models import Task, Fav
from todolist.owner import OwnerListView, OwnerDetailView , OwnerDeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.urls import reverse_lazy
from todolist.forms import CreateForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.db.models import Q

class TasksListView(OwnerListView):
    model = Task
    template_name = "todolist/task_list.html"


    def get(self, request) :
        strval =  request.GET.get("search", False)
        # ad_list = Ad.objects.all()
        if strval :
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            query.add(Q(tags__name__in=[strval]), Q.OR)
            task_list = Task.objects.filter(query).select_related().distinct().order_by('-updated_at')[:10]
        else :
            task_list = Task.objects.all()

        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_tasks.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]
        ctx = {'task_list' : task_list, 'favorites': favorites, 'search': strval}
        return render(request, self.template_name, ctx)


class TasksDetailView(OwnerDetailView):
    model = Task
    template_name = "todolist/task_detail.html"

class TasksCreateView(LoginRequiredMixin, View):
    template_name = 'todolist/task_form.html'
    success_url = reverse_lazy('todolist:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        task = form.save(commit=False)
        task.owner = self.request.user
        task.save()
        form.save_m2m()
        return redirect(self.success_url)

class TasksUpdateView(LoginRequiredMixin, View):
    template_name = 'todolist/task_form.html'
    success_url = reverse_lazy('todolist:all')

    def get(self, request, pk):
        task = get_object_or_404(Task, id=pk, owner=self.request.user)
        form = CreateForm(instance=task)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        task = get_object_or_404(Task, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=Task)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        task = form.save(commit=False)
        task.save()
        form.save_m2m()

        return redirect(self.success_url)


class TasksDeleteView(OwnerDeleteView):
    model = Task

# csrf exemption in class based views
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Add PK",pk)
        t = get_object_or_404(Task, id=pk)
        fav = Fav(user=request.user, ad=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        print("Delete PK",pk)
        t = get_object_or_404(Task, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, ad=t).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

ToDoList_Project/todolist/templates/todolist/task_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete task</h1>

<p>Are you sure you want to delete the task: {{ Task }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

ToDoList_Project/todolist/templates/todolist/task_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}

<span style="float: right;">
({{ task.updated_at|naturaltime }})
{% if task.owner == user %}
<a href="{% url 'todolist:task_update' task.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'todolist:task_delete' task.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ task.title }}</h1>
<p>
{{ task.text }}
</p>
{% if task.tags.all %}
<p>Tags:
  {% for tag in task.tags.all %}
  <span style="border:1px grey solid; background-color: LightGreen;">{{ tag }}</span>
  {% endfor %}
</p>
{% endif %}

<p>
<a href="{% url 'todolist:all' %}">All tasks</a>
</p>
{% endblock %}

ToDoList_Project/todolist/templates/todolist/task_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'todolist:all' %}';return false;">
  </form>
</p>
{% endblock %}

ToDoList_Project/todolist/templates/todolist/task_list.html
{% extends "todolist_menu.html" %}
{% block content %}
<h1>Tasks</h1>

<p>

{% if user.is_authenticated %}
  <div style="float:right">
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
    <form>
      <input type="text" placeholder="Search.." name="search"
      {% if search %} value="{{ search }}" {% endif %}>
      <button type="submit"><i class="fa fa-search"></i></button>
      <a href="{% url 'todolist:all' %}"><i class="fa fa-undo"></i></a>
    </form>
  </div>
  {% if task_list %}
  <ul>
    {% for task in task_list %}
      <li>
          {% if task.owner == user %}
          <a href="{% url 'todolist:task_detail'  task.id %}">{{ task.title }}</a>
          (<a href="{% url 'todolist:task_update' task.id %}">Edit</a> |
          <a href="{% url 'todolist:task_delete' task.id %}">Delete</a>)
          {% endif %}

          <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
          <a href="#" onclick=
              "favPost('{% url 'todolist:task_unfavorite' task.id %}', {{ task.id }} );return false;"
              {% if task.id not in favorites %} style="display: none;" {% endif %}
              id="favorite_star_{{task.id}}">
          <span class="fa-stack" style="vertical-align: middle;">
          <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
          <i class="fa fa-star-o fa-stack-1x"></i>
          </span>
          </a>
          <!-- the second href -->
          <a href="#" onclick=
              "favPost('{% url 'todolist:task_favorite' task.id %}', {{ task.id }} );return false;"
              {% if task.id in favorites %} style="display: none;" {% endif %}
              id="unfavorite_star_{{task.id}}">
          <span class="fa-stack" style="vertical-align: middle;">
          <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
          <i class="fa fa-star-o fa-stack-1x"></i>
          </span>
          </a>

      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no tasks in the database.</p>
  {% endif %}
{% else %}
  <p>Please log in first.</p>
{% endif %}
</p>
<p>
<a href="{% url 'todolist:task_create' %}">Add a task</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'todolist:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'todolist:all' %}">Login</a>
{% endif %}
</p>
<script>
function favPost(url, task_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+task_id).toggle();
        $("#favorite_star_"+task_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>

{% endblock %}